### ISSUE TITLE
LetsEncrypt: Connection refused

### ISSUE THREAD

**Issue by daurrutia** [openemr/openemr-devops#115]
Receiving a "Connection refused" error when attempting to run "docker-compose up" on modified docker-compose.yml (DOMAIN and EMAIL env vars).

Verified port 80 and 443 are open to the internet.

Am I going about it the wrong way?
 
--------------------------------------------------------------------------

 Plugins selected: Authenticator webroot, Installer None
openemr_1  | Obtaining a new certificate
openemr_1  | Performing the following challenges:
openemr_1  | http-01 challenge for openemr.mydomain.com
openemr_1  | Using the webroot path /var/www/localhost/htdocs/openemr for all unmatched domains.
openemr_1  | Waiting for verification...
openemr_1  | Cleaning up challenges
openemr_1  | IMPORTANT NOTES:
openemr_1  | Failed authorization procedure. openemr.mydomain.com (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://openemr.mydomain.com/.well-known/acme-challenge/xR4iR_ekS4um9XQDgp-tiuZg6pviRJ70LDGS_P_Md1s: Connection refused
openemr_1  |  - The following errors were reported by the server:
openemr_1  |
openemr_1  |    Domain: openemr.mydomain.com
openemr_1  |    Type:   connection
openemr_1  |    Detail: Fetching
openemr_1  |    http://openemr.mydomain.com/.well-known/acme-challenge/xR4iR_ekS4um9XQDgp-tiuZg6pviRJ70LDGS_P_Md1s:
openemr_1  |    Connection refused
openemr_1  |
openemr_1  |    To fix these errors, please make sure that your domain name was
openemr_1  |    entered correctly and the DNS A/AAAA record(s) for that domain
openemr_1  |    contain(s) the right IP address. Additionally, please check that
openemr_1  |    your computer has a publicly routable IP address and that no
openemr_1  |    firewalls are preventing the server from communicating with the
openemr_1  |    client. If you're using the webroot plugin, you should also verify
openemr_1  |    that you are serving files from the webroot path you provided.
openemr_1  | WARNING: SETTING AN EMAIL VIA $EMAIL is HIGHLY RECOMMENDED IN ORDER TO
openemr_1  |          RECEIVE ALERTS FROM LETSENCRYPT ABOUT YOUR SSL CERTIFICATE.
openemr_1  | Saving debug log to /var/log/letsencrypt/letsencrypt.log

--------------------------------------------------------------------------
:~/openemr-devops/packages/lightsail# cat docker-compose.yml

```
version: '3.1'
services:
  mysql:
    restart: always
    image: openemr/mysql-xtrabackup:1.0.0
    command: ['mysqld','--character-set-server=utf8']
    volumes:
    - sqlbackup:/mnt/backups
    environment:
      MYSQL_ROOT_PASSWORD: root
  openemr:
    restart: always
    image: openemr/openemr:5.0.0
    ports:
    - 80:80
    - 443:443
    volumes:
    - logvolume01:/var/log
    - sitevolume:/var/www/localhost/htdocs/openemr/sites/default
    environment:
      DOMAIN: openemr.mydomain.com
      EMAIL: daurrutia@gmail.com
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASS: root
      MYSQL_USER: root
      MYSQL_PASS: root
      OE_USER: admin
      OE_PASS: pass
    links:
    - mysql
volumes:
  logvolume01: {}
  sitevolume: {}
  sqlbackup: {}
```
--------------------------------------------------------------------------
