### ISSUE TITLE
Report that crond was not working in the docker for the ssl certbot cert renewals

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr-devops#401]
Report that crond was not working in the docker for the ssl certbot cert renewals.

Hi @adunsulag ,
Turns out this is set up in the dockers already and should be working when running docker with the letsencrypt ssl setting.
1. dcron package is installed in Dockerfile
2. ssl.sh is run when docker is started and that is where the certs and cron is set up (/etc/crontabs/root population and start of crond service).

So to test this, would need to bring the docker up with a $DOMAIN setting.

Hopefully it's not broken, although i don't have a quick way to test this in my testing environment. Are you able to test with a $DOMAIN setting?

**Comment by adunsulag** [comment]
Yes, I was using the DOMAIN setting. Here's a snippet of the docker I am using which I just had to recently renew the certificate on.
```

    volumes:
    - ../..:/openemr:ro
    - ../..:/var/www/localhost/htdocs/openemr:rw
    - publicvolume:/var/www/localhost/htdocs/openemr/public:rw
    - sitesvolume:/var/www/localhost/htdocs/openemr/sites:rw
    - nodemodules:/var/www/localhost/htdocs/openemr/node_modules:rw
    - vendordir:/var/www/localhost/htdocs/openemr/vendor:rw
    - ccdanodemodules:/var/www/localhost/htdocs/openemr/ccdaservice/node_modules:rw
    - logvolume:/var/log
    - couchdbvolume:/couchdb/data
    environment:
      DOMAIN: openemr.discoverandchange.net
      EMAIL: snielson@discoverandchange.com
```
